### ISSUE TITLE
AttributeError: 'GraphModule' object has no attribute 'weight'  - `flan-t5-small` dynamic quantization

### ISSUE THREAD

**Issue by jmdu99** [huggingface/optimum-intel#212]
Hello,

I have applied dynamic quantization to a `flan-t5-small` model and I get this error during the evaluation of the model:

> AttributeError: 'GraphModule' object has no attribute 'weight'

The error happens in the `generate` function of the following code snippet:

```
from optimum.intel.neural_compressor import INCModelForSeq2SeqLM

model = INCModelForSeq2SeqLM.from_pretrained(model_name).to(device)

for examples_chunk in tqdm(list(chunks(examples, batch_size))):
        examples_chunk = [prefix + text for text in examples_chunk]
        batch = tokenizer(examples_chunk, return_tensors="pt", truncation=True, padding="longest").to(device)
        summaries = model.generate(
                    input_ids=batch.input_ids,
                    attention_mask=batch.attention_mask,
                    **generate_kwargs,
        )
```

Note that I have not found this error with quantized BART models. 

This is the traceback:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mrshu/transformers/examples/research_projects/seq2seq-distillation/run_eval.py:187 in      │
│ <module>                                                                                         │
│                                                                                                  │
│   184 if __name__ == "__main__":                                                                 │
│   185 │   # Usage for MT:                                                                        │
│   186 │   # python run_eval.py MODEL_NAME $DATA_DIR/test.source $save_dir/test_translations.tx   │
│ ❱ 187 │   run_generate(verbose=True)                                                             │
│   188                                                                                            │
│                                                                                                  │
│ /home/mrshu/transformers/examples/research_projects/seq2seq-distillation/run_eval.py:146 in      │
│ run_generate                                                                                     │
│                                                                                                  │
│   143 │   Path(args.save_path).parent.mkdir(exist_ok=True)                                       │
│   144 │   if args.reference_path is None and Path(args.score_path).exists():                     │
│   145 │   │   warnings.warn(f"score_path {args.score_path} will be overwritten unless you type   │
│ ❱ 146 │   runtime_metrics = generate_summaries_or_translations(                                  │
│   147 │   │   examples,                                                                          │
│   148 │   │   args.save_path,                                                                    │
│   149 │   │   args.model_name,                                                                   │
│                                                                                                  │
│ /home/mrshu/transformers/examples/research_projects/seq2seq-distillation/run_eval.py:69 in       │
│ generate_summaries_or_translations                                                               │
│                                                                                                  │
│    66 │   for examples_chunk in tqdm(list(chunks(examples, batch_size))):                        │
│    67 │   │   examples_chunk = [prefix + text for text in examples_chunk]                        │
│    68 │   │   batch = tokenizer(examples_chunk, return_tensors="pt", truncation=True, padding=   │
│ ❱  69 │   │   summaries = model.generate(                                                        │
│    70 │   │   │   input_ids=batch.input_ids,                                                     │
│    71 │   │   │   attention_mask=batch.attention_mask,                                           │
│    72 │   │   │   **generate_kwargs,                                                             │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27 in             │
│ decorate_context                                                                                 │
│                                                                                                  │
│    24 │   │   @functools.wraps(func)                                                             │
│    25 │   │   def decorate_context(*args, **kwargs):                                             │
│    26 │   │   │   with self.clone():                                                             │
│ ❱  27 │   │   │   │   return func(*args, **kwargs)                                               │
│    28 │   │   return cast(F, decorate_context)                                                   │
│    29 │                                                                                          │
│    30 │   def _wrap_generator(self, func):                                                       │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/generation/utils.py:1252 in      │
│ generate                                                                                         │
│                                                                                                  │
│   1249 │   │   if self.config.is_encoder_decoder and "encoder_outputs" not in model_kwargs:      │
│   1250 │   │   │   # if model is encoder decoder encoder_outputs are created                     │
│   1251 │   │   │   # and added to `model_kwargs`                                                 │
│ ❱ 1252 │   │   │   model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(           │
│   1253 │   │   │   │   inputs_tensor, model_kwargs, model_input_name                             │
│   1254 │   │   │   )                                                                             │
│   1255                                                                                           │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/generation/utils.py:617 in       │
│ _prepare_encoder_decoder_kwargs_for_generation                                                   │
│                                                                                                  │
│    614 │   │   model_input_name = model_input_name if model_input_name is not None else self.ma  │
│    615 │   │   encoder_kwargs["return_dict"] = True                                              │
│    616 │   │   encoder_kwargs[model_input_name] = inputs_tensor                                  │
│ ❱  617 │   │   model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)          │
│    618 │   │                                                                                     │
│    619 │   │   return model_kwargs                                                               │
│    620                                                                                           │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1194 in _call_impl │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:1055 in │
│ forward                                                                                          │
│                                                                                                  │
│   1052 │   │   │   │   │   None,  # past_key_value is always None with gradient checkpointing    │
│   1053 │   │   │   │   )                                                                         │
│   1054 │   │   │   else:                                                                         │
│ ❱ 1055 │   │   │   │   layer_outputs = layer_module(                                             │
│   1056 │   │   │   │   │   hidden_states,                                                        │
│   1057 │   │   │   │   │   attention_mask=extended_attention_mask,                               │
│   1058 │   │   │   │   │   position_bias=position_bias,                                          │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1194 in _call_impl │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:739 in  │
│ forward                                                                                          │
│                                                                                                  │
│    736 │   │   │   attention_outputs = attention_outputs + cross_attention_outputs[2:]           │
│    737 │   │                                                                                     │
│    738 │   │   # Apply Feed Forward layer                                                        │
│ ❱  739 │   │   hidden_states = self.layer[-1](hidden_states)                                     │
│    740 │   │                                                                                     │
│    741 │   │   # clamp inf values to enable fp16 training                                        │
│    742 │   │   if hidden_states.dtype == torch.float16 and torch.isinf(hidden_states).any():     │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1194 in _call_impl │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:336 in  │
│ forward                                                                                          │
│                                                                                                  │
│    333 │                                                                                         │
│    334 │   def forward(self, hidden_states):                                                     │
│    335 │   │   forwarded_states = self.layer_norm(hidden_states)                                 │
│ ❱  336 │   │   forwarded_states = self.DenseReluDense(forwarded_states)                          │
│    337 │   │   hidden_states = hidden_states + self.dropout(forwarded_states)                    │
│    338 │   │   return hidden_states                                                              │
│    339                                                                                           │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1194 in _call_impl │
│                                                                                                  │
│   1191 │   │   # this function, and just call forward.                                           │
│   1192 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1193 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1194 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1195 │   │   # Do not call functions when jit is used                                          │
│   1196 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1197 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:316 in  │
│ forward                                                                                          │
│                                                                                                  │
│    313 │   │   # To make 8bit quantization work for google/flan-t5-xxl, self.wo is kept in floa  │
│    314 │   │   # See https://github.com/huggingface/transformers/issues/20287                    │
│    315 │   │   # we also make sure the weights are not in `int8` in case users will force `_kee  │
│ ❱  316 │   │   if hidden_states.dtype != self.wo.weight.dtype and self.wo.weight.dtype != torch  │
│    317 │   │   │   hidden_states = hidden_states.to(self.wo.weight.dtype)                        │
│    318 │   │                                                                                     │
│    319 │   │   hidden_states = self.wo(hidden_states)                                            │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1269 in            │
│ __getattr__                                                                                      │
│                                                                                                  │
│   1266 │   │   │   modules = self.__dict__['_modules']                                           │
│   1267 │   │   │   if name in modules:                                                           │
│   1268 │   │   │   │   return modules[name]                                                      │
│ ❱ 1269 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1270 │   │   │   type(self).__name__, name))                                                   │
│   1271 │                                                                                         │
│   1272 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'GraphModule' object has no attribute 'weight'
```

These are my dependencies:

```
Name: torch
Version: 1.13.1

Name: pytorch-lightning
Version: 1.9.3

Name: transformers
Version: 4.26.1

Name: optimum
Version: 1.7.0

Name: optimum-intel
Version: 1.7.1.dev0

Name: neural-compressor
Version: 2.0
```

**Comment by jmdu99** [comment]
UPDATE:
I think [this PR](https://github.com/huggingface/transformers/pull/21843/files#diff-ebaff1224cad711fd3cefb771ce17d1392ae2dfc7f74dc7da9dd014d7642a344) solves the issue

**Comment by jmdu99** [comment]
**UPDATE:**

I upgraded transformers version to `transformers-4.27.0.dev0` since a [change](https://github.com/huggingface/transformers/pull/21843) in `models/t5/modeling_t5.py` was made due to a problem related to Pytorch dynamic quantization: https://github.com/huggingface/transformers/issues/21839

However, I still get the same error:

```
 /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:320 in  │
│ forward                                                                                          │
│                                                                                                  │
│    317 │   │   # See https://github.com/huggingface/transformers/issues/20287                    │
│    318 │   │   # we also make sure the weights are not in `int8` in case users will force `_kee  │
│    319 │   │   if (                                                                              │
│ ❱  320 │   │   │   isinstance(self.wo.weight, torch.Tensor)                                      │
│    321 │   │   │   and hidden_states.dtype != self.wo.weight.dtype                               │
│    322 │   │   │   and self.wo.weight.dtype != torch.int8                                        │
│    323 │   │   ):                                                                                │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1269 in            │
│ __getattr__                                                                                      │
│                                                                                                  │
│   1266 │   │   │   modules = self.__dict__['_modules']                                           │
│   1267 │   │   │   if name in modules:                                                           │
│   1268 │   │   │   │   return modules[name]                                                      │
│ ❱ 1269 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1270 │   │   │   type(self).__name__, name))                                                   │
│   1271 │                                                                                         │
│   1272 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'GraphModule' object has no attribute 'weight'
```

**Comment by xin3he** [comment]
Hi, @jmdu99 , It's a known issue, please try transformers <= 4.26.0. we are planning to raise it to transformers.

**Comment by jmdu99** [comment]
Hi @xin3he, thanks for the answer. It works with `transformers-4.25.1`

Just FYI, it still fails with `transformers 4.26.0`:

```
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:313 in  │
│ forward                                                                                          │
│                                                                                                  │
│    310 │   │                                                                                     │
│    311 │   │   # To make 8bit quantization work for google/flan-t5-xxl, self.wo is kept in floa  │
│    312 │   │   # See https://github.com/huggingface/transformers/issues/20287                    │
│ ❱  313 │   │   if hidden_states.dtype != self.wo.weight.dtype:                                   │
│    314 │   │   │   hidden_states = hidden_states.to(self.wo.weight.dtype)                        │
│    315 │   │                                                                                     │
│    316 │   │   hidden_states = self.wo(hidden_states)                                            │
│                                                                                                  │
│ /home/mrshu/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py:1269 in            │
│ __getattr__                                                                                      │
│                                                                                                  │
│   1266 │   │   │   modules = self.__dict__['_modules']                                           │
│   1267 │   │   │   if name in modules:                                                           │
│   1268 │   │   │   │   return modules[name]                                                      │
│ ❱ 1269 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1270 │   │   │   type(self).__name__, name))                                                   │
│   1271 │                                                                                         │
│   1272 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'GraphModule' object has no attribute 'weight'
```

**Comment by xin3he** [comment]
@jmdu99 INC will release version 2.1 next Wednesday and you can use the new version.
