### ISSUE TITLE
llava-v1.6-mistral-7b-hf export failure

### ISSUE THREAD

**Issue by Wovchena** [huggingface/optimum-intel#1398]
`optimum-cli export openvino --model llava-hf/llava-v1.6-mistral-7b-hf ./i/llava-v1.6-mistral-7b-hf --trust-remote-code --weight-format fp16` fails with
```
Traceback (most recent call last):
  File "/home/vzlobin/z/e/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/commands/export/openvino.py", line 577, in run
    main_export(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/__main__.py", line 453, in main_export
    submodel_paths = export_from_model(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 786, in export_from_model
    export_models(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 557, in export_models
    export(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 195, in export
    return export_pytorch(
           ^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 457, in export_pytorch
    with patcher:
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/model_patcher.py", line 777, in __exit__
    for layer in self._model.model.layers:
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1940, in __getattr__
    raise AttributeError(
AttributeError: 'LlavaNextModel' object has no attribute 'layers'
```
for `transformers` 4.52.3 or 4.53.3. Works with 4.51.3.

**Comment by Wovchena** [comment]
Add tests. That not only eliminates the need to ask to verify the fix but also ensures it won't fail in future

**Comment by IlyasMoutawwakil** [comment]
unfortunately it has to be a tiny model, the github runners are slow dual-core cpus 😔
and we already had issues with the limited storage in the slow/full ci #1376
@nikita-savelyevv wdyt ?

**Comment by nikita-savelyevv** [comment]
A test obviously won't hurt, at least for llava-mistral only. The question is how complicated is it to add one. If just creating a tiny version of https://huggingface.co/llava-hf/llava-v1.6-mistral-7b-hf and inserting it to the test model list is enough, then I believe it's not a big deal.
