### PR TITLE
Transformers v5

### PR DESCRIPTION
**Pull request by echarlaix**
with https://github.com/huggingface/optimum/pull/2408/

List of architectures for which are deprecating support for transformers >= v5
(remote code modeling incompatible with v5)
- codegen2
- exaone
- decilm
- internlm2
- orion
- aquila2
- jais
- baichuan2
- internvl_chat
- minicpmv
(remote code models)
- aquila
- xverse
- internlm

List of architectures for which we removed support for transformers >= v5 for which support can be added later on
- xlm
- data2vec-text
- flaubert
- marian
- ~granitemoe~
- zamba2
- ~phimoe~ 
- drbx
- ~eagle3~
- mt5
- ~llava~
- idefics3
- ~gemma3~
- smolvlm
- got_ocr2
- llava_next_video
- llama4
- bitnet
- qwen3_next
- exaone4

### CODE REVIEW

File: optimum/exporters/openvino/model_configs.py [hunk 1]
```diff
@@ -259,14 +255,6 @@ def init_model_configs():
...
         "Gemma3ForConditionalGeneration",
     )
-    TasksManager._CUSTOM_CLASSES[("pt", "idefics3", "image-text-to-text")] = (
-        "transformers",
-        "AutoModelForImageTextToText",
-    )
-    TasksManager._CUSTOM_CLASSES[("pt", "smolvlm", "image-text-to-text")] = (
-        "transformers",
-        "AutoModelForImageTextToText",
-    )
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:272]: redundant (`"image-text-to-text"` -> `AutoModelForImageTextToText`)  so removing https://github.com/huggingface/optimum/blob/114647f51404f9747410afc287a8079f1f16389b/optimum/exporters/tasks.py#L157

File: .github/workflows/build_documentation.yml [hunk 2]
```diff
@@ -51,7 +51,7 @@ jobs:
         run: |
           pip install --upgrade pip uv
           uv pip install git+https://github.com/huggingface/doc-builder
-          uv pip install .[quality] nncf openvino neural-compressor[pt]>3.4 diffusers accelerate datasets
```
Comment (echarlaix) [inline .github/workflows/build_documentation.yml]: latest neural-compressor version (v3.7.1) incompatible with transformers v5 https://github.com/intel/neural-compressor/blob/1b867f0391a3ac4e0bd6cb514a3e165875e7feb9/neural_compressor/transformers/models/modeling_auto.py#L45

File: docs/source/neural_compressor/reference.mdx [hunk 3]
```diff
@@ -14,43 +14,3 @@ specific language governing permissions and limitations under the License.
 `optimum.intel.neural_compressor` is deprecated and will be removed in the next major release.
 
 </Tip>
-
-## INCQuantizer
```
Comment (echarlaix) [inline docs/source/neural_compressor/reference.mdx]: resulting from https://github.com/huggingface/optimum-intel/pull/1589/files#r2728526410, neural-compressor integration is deprecated so removing

File: .github/workflows/build_pr_documentation.yml [hunk 4]
```diff
@@ -38,7 +38,8 @@ jobs:
         run: |
           pip install --upgrade pip uv
           uv pip install git+https://github.com/huggingface/doc-builder
-          uv pip install .[quality] nncf openvino neural-compressor[pt]>3.4 diffusers accelerate datasets
+          uv pip install transformers==4.57.6
```
Comment (echarlaix) [inline .github/workflows/build_pr_documentation.yml]: needed until next diffusers release as latest diffusers version (v0.36.0) incompatible with transformers v5

File: optimum/exporters/openvino/model_patcher.py [hunk 5]
```diff
@@ -54,6 +55,118 @@
 logger = logging.getLogger(__name__)
 
 
+class OVDynamicCache(DynamicCache):
+    # copied from https://github.com/huggingface/transformers/blob/v4.57.6/src/transformers/cache_utils.py#L1005
+    def to_legacy_cache(self) -> tuple[tuple[torch.Tensor, torch.Tensor]]:
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_patcher.py]: all these methods deprecated in https://github.com/huggingface/transformers/pull/41378/

File: tests/openvino/test_decoder.py [hunk 6]
```diff
@@ -147,6 +146,9 @@ class OVModelForCausalLMIntegrationTest(unittest.TestCase):
     if is_transformers_version("<", "4.56.0"):
         SUPPORTED_ARCHITECTURES += ("qwen", "chatglm", "chatglm4")
 
+    if is_transformers_version("<", "5"):
+        SUPPORTED_ARCHITECTURES += ("codegen2",)
```
Comment (echarlaix) [inline tests/openvino/test_decoder.py]: remote modeling code incompatible with transformers v5 https://huggingface.co/Salesforce/codegen2-7B_P/blob/main/configuration_codegen.py#L21

File: optimum/exporters/openvino/model_patcher.py [hunk 7]
```diff
@@ -7377,10 +7522,12 @@ def patch_sparse_moe(sparse_moe_layer):
         super().__enter__()
         setattr(self._model, self.orig_forward_name, self.patched_forward)
 
-        self._model.model._orig_update_causal_mask = self._model.model._update_causal_mask
-        self._model.model._update_causal_mask = types.MethodType(
-            granite_moe_hybrid_update_causal_mask, self._model.model
-        )
+        if is_transformers_version("<", "5"):
+            self._model.model._orig_update_causal_mask = self._model.model._update_causal_mask
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_patcher.py:7677]: removed  in https://github.com/huggingface/transformers/pull/40132/

File: optimum/exporters/openvino/model_patcher.py [hunk 8]
```diff
@@ -2671,15 +2793,19 @@ def gptj_attn_forward(
     if output_attentions:
         self._attn = self._orig_attn
 
+    kwargs = {}
+    if is_transformers_version("<", "5"):
+        kwrags["head_mask"] = head_mask
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_patcher.py]: removed in https://github.com/huggingface/transformers/pull/41076

File: tests/openvino/test_modeling.py [hunk 9]
```diff
@@ -726,20 +727,21 @@ def test_load_model_from_hub(self):
         gc.collect()
 
     def test_seq2seq_load_from_hub(self):
-        model_id = "echarlaix/tiny-random-t5"
+        model_id = MODEL_NAMES["whisper"]
+        task = "automatic-speech-recognition"
         # verify could load both pytorch and openvino model (export argument should automatically infered)
-        ov_exported_pipe = optimum_pipeline("text2text-generation", model_id, accelerator="openvino")
```
Comment (echarlaix) [inline tests/openvino/test_modeling.py:731]: text2text-generation pipeline removed in https://github.com/huggingface/transformers/pull/43256/

File: optimum/intel/openvino/modeling_base.py [hunk 10]
```diff
@@ -261,21 +265,21 @@ def __init__(
         if self.can_generate():
             self.generation_config = generation_config or GenerationConfig.from_model_config(config)
 
-            # some model configs may have issues with loading without parameters initialization
-            try:
-                misplaced_generation_parameters = self.config._get_non_default_generation_parameters()
```
Comment (echarlaix) [inline optimum/intel/openvino/modeling_base.py:266]: `_get_non_default_generation_parameters` removed in https://github.com/huggingface/transformers/pull/42702

File: optimum/intel/openvino/modeling_base.py [hunk 11]
```diff
@@ -261,21 +265,21 @@ def __init__(
...
-            except (KeyError, TypeError):
-                misplaced_generation_parameters = {}
-            if len(misplaced_generation_parameters) > 0:
```
Comment (echarlaix) [inline optimum/intel/openvino/modeling_base.py:269]: misplaced_generation_parameters removed in https://github.com/huggingface/transformers/pull/41695/

File: tests/openvino/test_seq2seq.py [hunk 12]
```diff
@@ -555,9 +570,13 @@ class OVModelForVisualCausalLMIntegrationTest(OVSeq2SeqTestMixin):
...
 
-    if is_transformers_version(">=", "4.54.0"):
+    if is_transformers_version("<", "4.54.0"):
         # remote code models differs after transformers v4.54
-        SUPPORTED_ARCHITECTURES = set(SUPPORTED_ARCHITECTURES) - {"llava-qwen2", "phi3_v", "phi4mm"}
+        SUPPORTED_ARCHITECTURES += ["llava-qwen2", "phi3_v"]
+
+    if is_transformers_version("<", "5"):
+        # remote code models incompatible after transformers v5
+        SUPPORTED_ARCHITECTURES += ["internvl_chat", "minicpmv"]
```
Comment (echarlaix) [inline tests/openvino/test_seq2seq.py:608]: remote code models incompatible with v5
- minicpmv : `all_tied_weights_keys` introduced in https://github.com/huggingface/transformers/pull/42270 `AttributeError: 'MiniCPMV' object has no attribute 'all_tied_weights_keys'`
- internvl_chat  https://huggingface.co/optimum-intel-internal-testing/tiny-random-internvl2/blob/main/modeling_intern_vit.py#L334  `RuntimeError: Tensor.item() cannot be called on meta tensors`

File: optimum/exporters/openvino/model_configs.py [hunk 13]
```diff
@@ -843,6 +844,7 @@ class GptOssOpenVINOConfig(LlamaOpenVINOConfig):
 )
 class BitnetOpenVINOConfig(LlamaOnnxConfig):
     MIN_TRANSFORMERS_VERSION = "4.52.1"
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:848]: incompatible with transformers v5.0, cannot run https://github.com/huggingface/transformers/blob/v5.0.0/tests/models/bitnet/test_modeling_bitnet.py#L175

File: optimum/exporters/openvino/model_configs.py [hunk 14]
```diff
@@ -858,7 +860,7 @@ class BitnetOpenVINOConfig(LlamaOnnxConfig):
     library_name="transformers",
 )
 class ExaoneOpenVINOConfig(LlamaOpenVINOConfig):
-    pass
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:864]: incompatible with v5 https://huggingface.co/optimum-intel-internal-testing/tiny-random-exaone/blob/main/modeling_exaone.py#L34 (`from_legacy_cache` deprecated)

File: optimum/exporters/openvino/model_configs.py [hunk 15]
```diff
@@ -1015,6 +1017,7 @@ class Starcoder2OpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
 @register_in_tasks_manager("internlm2", *["text-generation", "text-generation-with-past"], library_name="transformers")
 class InternLM2OpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
     DEFAULT_ONNX_OPSET = 14
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:1038]: incompatible with v5 https://huggingface.co/internlm/internlm2_5-7b/blob/main/modeling_internlm2.py#L273 coming from https://github.com/huggingface/transformers/pull/39847/ `rope_scaling` -> `rope_parameters` (also key is now `rope_type` instead of `type`)

File: optimum/exporters/openvino/model_configs.py [hunk 16]
```diff
@@ -1024,7 +1027,7 @@ class InternLM2OpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
 @register_in_tasks_manager("orion", *["text-generation", "text-generation-with-past"], library_name="transformers")
 class OrionOpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
     DEFAULT_ONNX_OPSET = 14
-
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:1048]: see https://github.com/huggingface/optimum-intel/pull/1589/changes#r2813566236

File: optimum/exporters/openvino/model_configs.py [hunk 17]
```diff
@@ -1321,6 +1324,7 @@ class CodeGenOpenVINOConfig(CodeGenOnnxConfig):
 )
 class DBRXOpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
     DEFAULT_ONNX_OPSET = 14
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:1348]: incompatible with v5.0, coming from https://github.com/huggingface/transformers/blob/v5.0.0/src/transformers/utils/loading_report.py#L248

`hidden_size` vs `d_model` size mismatch https://huggingface.co/optimum-intel-internal-testing/tiny-random-dbrx/blob/main/config.json#L12 https://github.com/huggingface/transformers/blob/v5.0.0/src/transformers/models/dbrx/configuration_dbrx.py#L84

File: optimum/exporters/openvino/model_configs.py [hunk 18]
```diff
@@ -1340,6 +1344,7 @@ class DBRXOpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
 )
 class JaisOpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
     DEFAULT_ONNX_OPSET = 14
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:1368]: modeling code incompatible with v5 : https://huggingface.co/optimum-intel-internal-testing/tiny-random-jais/blob/main/modeling_jais.py#L38

File: optimum/exporters/openvino/model_configs.py [hunk 19]
```diff
@@ -1508,6 +1513,7 @@ def generate(self, input_name: str, framework: str = "pt", int_dtype: str = "int
 @register_in_tasks_manager("deci", *["text-generation", "text-generation-with-past"], library_name="transformers")
 class DeciOpenVINOConfig(TextDecoderWithPositionIdsOnnxConfig):
     DEFAULT_ONNX_OPSET = 14
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:1537]: modeling code incompatible with v5 : https://huggingface.co/Deci/DeciLM-7B/blob/main/transformers_v4_35_2__modeling_llama.py#L43

File: optimum/exporters/openvino/model_configs.py [hunk 20]
```diff
@@ -2060,11 +2072,16 @@ def get_model_for_behavior(self, model, behavior: Union[str, VLMConfigBehavior])
...
 
+        if behavior == VLMConfigBehavior.LANGUAGE:
+            return model.language_model
+
         return super().get_model_for_behavior(model, behavior)
 
 
 @register_in_tasks_manager("internvl_chat", *["image-text-to-text"], library_name="transformers")
 class InternVLChatOpenVINOConfig(BaseVLMOpenVINOConfig):
+    MAX_TRANSFORMERS_VERSION = "4.57.6"
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_configs.py:2100]: incompatible with v5 https://huggingface.co/optimum-intel-internal-testing/tiny-random-internvl2/blob/main/modeling_intern_vit.py#L334

File: optimum/exporters/openvino/model_patcher.py [hunk 21]
```diff
@@ -2697,15 +2721,19 @@ def gptj_attn_forward(
     if output_attentions:
         self._attn = self._orig_attn
 
+    kwargs = {}
+    if is_transformers_version("<", "5"):
+        kwargs["head_mask"] = head_mask
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_patcher.py:2816]: head_mask removed in gptj https://github.com/huggingface/transformers/pull/41076

File: optimum/intel/openvino/__init__.py [hunk 22]
```diff
@@ -35,8 +35,12 @@
 
 warnings.simplefilter(action="ignore", category=FutureWarning)
 
+
+logger = logging.getLogger(__name__)
+
+
 if is_openvino_version("<", "2025.4.0"):
-    raise ImportError(
+    logger.warning(
```
Comment (echarlaix) [inline optimum/intel/openvino/__init__.py:43]: using openvino v2025.3.0 for modeling tests https://github.com/huggingface/optimum-intel/actions/runs/21860303394/job/63087382821

File: .github/workflows/build_documentation.yml [hunk 23]
```diff
@@ -51,6 +51,7 @@ jobs:
         run: |
           pip install --upgrade pip uv
           uv pip install git+https://github.com/huggingface/doc-builder
+          uv pip install transformers==4.57.6
           uv pip install .[quality] neural-compressor[pt]>3.4 diffusers accelerate datasets
```
Comment (IlyasMoutawwakil) [inline .github/workflows/build_documentation.yml]: can't we use the diffusers extra defined in setup.py here ? would avoid us forgetting any pins

File: .github/workflows/test_openvino.yml [hunk 24]
```diff
@@ -54,14 +54,29 @@ jobs:
       - name: Install dependencies
         run: |
           pip install --upgrade pip uv
-          uv pip install .[diffusers,tests]
+          uv pip install .[tests] librosa diffusers
+
+      - if: ${{ matrix.test-pattern == '*modeling*' }}
+        name: Install OpenVINO
+        run: |
+          uv pip install openvino==2025.3.0 openvino-tokenizers==2025.3.0
```
Comment (IlyasMoutawwakil) [inline .github/workflows/test_openvino.yml:62]: is this for some specific model failing that's failing with latest OV ?

File: optimum/exporters/openvino/model_configs.py [hunk 25]
```diff
@@ -282,15 +253,45 @@ def init_model_configs():
...
+            "Gemma3ForConditionalGeneration",
+        )
+
+    # since transformers v4.52, model can be loaded using default AutoModelForImageTextToText
+    # https://github.com/huggingface/transformers/blob/v4.52.0/src/transformers/models/auto/modeling_auto.py#L899
+    if is_transformers_version("<", "4.52"):
+        TasksManager._CUSTOM_CLASSES[("pt", "llava_next_video", "image-text-to-text")] = (
+            "transformers",
+            "AutoModelForVision2Seq",
+        )
```
Comment (IlyasMoutawwakil) [inline optimum/exporters/openvino/model_configs.py:287]: nice !

File: optimum/exporters/openvino/model_patcher.py [hunk 26]
```diff
@@ -4435,28 +4507,35 @@ def _granite_moe_parallel_experts_forward(self, inputs, expert_size):
...
+                block_sparse_moe.input_linear.forward = types.MethodType(
+                    _granite_moe_parallel_experts_forward, block_sparse_moe.input_linear
+                )
+                block_sparse_moe.output_linear._orig_forward = block_sparse_moe.output_linear.forward
+                block_sparse_moe.output_linear.forward = types.MethodType(
+                    _granite_moe_parallel_experts_forward, block_sparse_moe.output_linear
+                )
+
+        else:
+            self._model.set_experts_implementation("batched_mm")
```
Comment (IlyasMoutawwakil) [inline optimum/exporters/openvino/model_patcher.py]: very nice ! just fyi, even though batching the experts/token pairs is exportable, and is faster than looping over all experts, it is still computationally very inefficient on CPU (see https://github.com/huggingface/transformers/pull/43438), supporting the grouped_mm operator from OV side is necessary @rkazants

File: optimum/intel/openvino/modeling_sam.py [hunk 27]
```diff
@@ -403,7 +403,7 @@ def get_image_wide_positional_embeddings(self):
         x_embed = x_embed / size
 
         positional_embedding = self.shared_image_embedding(torch.stack([x_embed, y_embed], dim=-1))
-        return positional_embedding.permute(2, 0, 1).unsqueeze(0)
+        return positional_embedding.permute(2, 0, 1).unsqueeze(0).detach()
```
Comment (IlyasMoutawwakil) [inline optimum/intel/openvino/modeling_sam.py:406]: is it necessary or to match transformers ?

File: optimum/intel/openvino/modeling_seq2seq.py [hunk 28]
```diff
@@ -56,6 +55,18 @@
...
+# AutoModelForVision2Seq is deprecated since v4.54
+# https://github.com/huggingface/transformers/blob/v4.54.0/src/transformers/models/auto/modeling_auto.py#L2151
+if is_transformers_version(">=", "4.54.0"):
+    from transformers import AutoModelForImageTextToText
+
+    transformers_auto_class = AutoModelForImageTextToText
+else:
+    from transformers import AutoModelForVision2Seq
+
+    transformers_auto_class = AutoModelForVision2Seq
```
Comment (IlyasMoutawwakil) [inline optimum/intel/openvino/modeling_seq2seq.py:67]: yeah we should probably deprecate vision2seq as well in favor of an image text to text

**Review by IlyasMoutawwakil — APPROVED** [review]
there are very few tests failing in the CI, great work @echarlaix ! LGTM

File: optimum/intel/openvino/modeling_seq2seq.py (hunk 28 above)
Comment (echarlaix) [reply optimum/intel/openvino/modeling_seq2seq.py:67]: yes, should be feasible once the min transformers supported version is v4.52

File: optimum/intel/openvino/modeling_sam.py (hunk 27 above)
Comment (echarlaix) [reply optimum/intel/openvino/modeling_sam.py:406]: this was added to fix inference for sam models for transformers v5 or higher (coming from https://github.com/huggingface/transformers/blob/196216c301dbf8f6199a46da9dabf8b82576824e/src/transformers/models/sam/modeling_sam.py#L550 to ensure the resulting tensor doesn't require grad)

File: .github/workflows/test_openvino.yml (hunk 24 above)
Comment (echarlaix) [reply .github/workflows/test_openvino.yml:62]: Yes this was added for the modeling tests that are currently failing with v2025.4 https://github.com/huggingface/optimum-intel/actions/runs/21860303394/job/63087382821, also removed the constraint of the openvino version https://github.com/huggingface/optimum-intel/pull/1589/changes#r2813603720

File: .github/workflows/build_documentation.yml (hunk 23 above)
Comment (echarlaix) [reply .github/workflows/build_documentation.yml]: the latest `neural-compressor` version (3.7) is also incompatible with transformers v5, this won't be an issue once we remove https://github.com/huggingface/optimum-intel/blob/main/docs/source/neural_compressor/reference.mdx

File: .github/workflows/test_offline.yaml [hunk 29]
```diff
@@ -34,15 +34,15 @@ jobs:
...
           HF_HOME=/tmp/ HF_HUB_OFFLINE=1 optimum-cli export openvino --model hf-internal-testing/tiny-random-gpt2 gpt2_openvino --task text-generation
 
-          huggingface-cli download hf-internal-testing/tiny-random-gpt2
+          hf download hf-internal-testing/tiny-random-gpt2
           HF_HUB_OFFLINE=1 optimum-cli export openvino --model hf-internal-testing/tiny-random-gpt2 gpt2_openvino --task text-generation
 
-          pytest tests/openvino/test_modeling.py -k "test_load_from_hub" -s -vvvvv
-          HF_HUB_OFFLINE=1 pytest tests/openvino/test_modeling.py -k "test_load_from_hub" -s -vvvvv
+          pytest tests/openvino/test_modeling.py -k "test_load_from_hub and not openclip" -s -vvvvv
+          HF_HUB_OFFLINE=1 pytest tests/openvino/test_modeling.py -k "test_load_from_hub and not openclip" -s -vvvvv
```
Comment (echarlaix) [inline .github/workflows/test_offline.yaml:48]: excluding openclip test for now : issue happens when loading tokenizer since v5 when offline mode (previously checking `tokenizer_config.json` and now looking for `config.json` which doesn't exist in https://huggingface.co/optimum-intel-internal-testing/tiny-open-clip-model) https://github.com/huggingface/optimum-intel/blob/2c48d6430c265ac259c1b264f3e2c4025cdd7b76/tests/openvino/test_modeling.py#L1604

File: tests/openvino/test_seq2seq.py [hunk 30]
```diff
@@ -391,11 +410,14 @@ def test_compare_to_transformers(self, model_arch):
     @parameterized.expand(SUPPORTED_ARCHITECTURES)
     @pytest.mark.run_slow
     @slow
+    @pytest.mark.skipif(
+        is_transformers_version("==", "5.0"), reason="Issue with transformers v5.0 coming from num_frames"
```
Comment (echarlaix) [inline tests/openvino/test_seq2seq.py:418]: issue coming from https://github.com/huggingface/transformers/blob/v4.57.6/src/transformers/pipelines/automatic_speech_recognition.py#L485 after `WhisperFeatureExtractor` stop generating `num_frames` in v5 https://github.com/huggingface/transformers/blob/v4.57.6/src/transformers/models/whisper/feature_extraction_whisper.py#L342

File: tests/openvino/test_seq2seq.py [hunk 31]
```diff
@@ -391,11 +414,14 @@ def test_compare_to_transformers(self, model_arch):
...
```
[the remark this answers is not in the document]
Comment (echarlaix) [reply tests/openvino/test_seq2seq.py:418]: fixed in v5.1 so should be disabled for v5.0 only

File: tests/openvino/test_decoder.py [hunk 32]
```diff
@@ -286,20 +305,34 @@ def test_find_untested_architectures(self):
...
+        if is_transformers_version(">", str(AfmoeOpenVINOConfig.MAX_TRANSFORMERS_VERSION)):
+            supported_architectures -= {"afmoe"}
         if is_transformers_version("<", str(BitnetOpenVINOConfig.MIN_TRANSFORMERS_VERSION)):
             supported_architectures -= {"bitnet"}
         if is_transformers_version("<", str(LFM2OpenVINOConfig.MIN_TRANSFORMERS_VERSION)):
             supported_architectures -= {"lfm2"}
 
         # qwen3_vl_text a part of qwen3_vl architecture and is tested in seq2seq group
-        if is_transformers_version(">=", str(Qwen3VLOpenVINOConfig.MIN_TRANSFORMERS_VERSION)):
+        if is_transformers_version(">", str(Qwen3VLOpenVINOConfig.MIN_TRANSFORMERS_VERSION)):
```
[the remark this answers is not in the document]
Comment (echarlaix) [reply tests/openvino/test_decoder.py]: fixed in https://github.com/huggingface/optimum-intel/pull/1589/changes/4a8644d937989fa88031b2c46992a5e48f4b8ac2

File: .github/workflows/test_openvino.yml (hunk 24 above)
Comment (rkazants) [inline .github/workflows/test_openvino.yml:62]:
```suggestion
          uv pip install openvino==2026.0 openvino-tokenizers==2026.0
```

File: optimum/intel/openvino/configuration.py [hunk 33]
```diff
@@ -556,6 +546,7 @@ class OVQuantizationMethod(str, Enum):
                 "__module.layers.27.mlp.up_proj/aten::linear/MatMul",
                 "__module.layers.27.mlp.gate_proj/aten::linear/MatMul",
             ],
+            "validate": False,
```
Comment (echarlaix) [inline optimum/intel/openvino/configuration.py:559]: this is needed as for models exported with transformers >= v5 https://huggingface.co/Qwen/Qwen3-Embedding-0.6B/blob/main/config.json#L25 will be loaded in bfloat16 and patched https://github.com/openvinotoolkit/openvino/blob/2026.0.1/src/bindings/python/src/openvino/frontend/pytorch/patch_model.py, for these models we need to use a different default ignored scope config (aten -> ov_ext) depending on what tranformers version was used during the export phase, otherwise quantization is failing at https://github.com/openvinotoolkit/nncf/blob/2f40a6dbc451c6ed025e012dfe65b2d577fde47f/src/nncf/scopes.py#L249. For now one option is to set validate to False as it only concerns Qwen/Qwen3-Embedding-0.6B @rkazants let me know if this works

File: optimum/exporters/openvino/model_patcher.py [hunk 34]
```diff
@@ -7103,11 +7194,16 @@ def lfm2_short_conv_forward_patched(
...
     seqlen = x.shape[1]
 
-    x = apply_mask_to_padding_states(x, attention_mask)
+    # only apply apply_mask_to_padding_states during the prefill phase
+    # https://github.com/huggingface/transformers/blob/v5.0.0/src/transformers/models/lfm2/modeling_lfm2.py#L427
+    # in transformers < v5 attention_mask was never applied in Lfm2ShortConv https://github.com/huggingface/transformers/blob/v4.57.6/src/transformers/models/lfm2/modeling_lfm2.py#L485
+    # until a fix was added in https://github.com/huggingface/transformers/pull/41790/
+    dtype = x.dtype
+    is_decoding = torch.tensor(seqlen == 1, dtype=dtype)
+    x = (x * (attention_mask[:, :seqlen, None] * (1 - is_decoding) + is_decoding)).to(dtype)
```
Comment (echarlaix) [inline optimum/exporters/openvino/model_patcher.py]: @popovaan let me know if this fix works for you, following https://github.com/huggingface/optimum-intel/pull/1643/changes/97fb4d545859072de013c795501e0d14ce2f385a

Comment (popovaan) [reply optimum/exporters/openvino/model_patcher.py]: Works great, thank you!

Comment (echarlaix) [reply optimum/exporters/openvino/model_patcher.py]: thanks a lot @popovaan for finding + fixing

File: optimum/exporters/openvino/convert.py [hunk 35]
```diff
@@ -687,10 +687,6 @@ def export_from_model(
         )
         logging.disable(logging.NOTSET)
 
-    # Remove empty model and export_configs pairs, they can be empty when a config class is shared between model versions.
-    # Example: Qwen2VL and Qwen3VL share config class, but "vision_embeddings_pos" is used in Qwen3VL only.
-    models_and_export_configs = {k: v for k, v in models_and_export_configs.items() if v != (None, None)}
```
Comment (echarlaix) [inline optimum/exporters/openvino/convert.py:692]: @popovaan I think we should remove as long as `Qwen2VLOpenVINOConfig` is updated accordingly, please confirm that this works for you (it was originally added in https://github.com/huggingface/optimum-intel/pull/1551)

Comment (popovaan) [reply optimum/exporters/openvino/convert.py:692]: Yes, I checked Qwen3VL and Qwen2.5VL models, they work fine on your branch.

File: setup.py [hunk 36]
```diff
@@ -33,8 +33,8 @@
     "setuptools",
     "huggingface-hub>=0.23.2,<2.0",
     "nncf>=2.19.0",
-    "openvino>=2025.4.0",
-    "openvino-tokenizers>=2025.4.0",
+    "openvino>=2025.4.0,<2026.1",
+    "openvino-tokenizers>=2025.4.0,<2026.1",
```
Comment (echarlaix) [inline setup.py]: not related to this PR : v2026.1 is breaking couple of export (granitemoehybrid, zamba2, xglm, llama4,...) on main, needs to be added temporarily and support can added back once fixed

Comment (rkazants) [reply setup.py]: Do these model work with transformers v4 and OV 2026.1.0 releases?

File: .github/workflows/test_offline.yaml [hunk 37]
```diff
@@ -34,15 +34,15 @@ jobs:
       - name: Install dependencies
         run: |
           pip install --upgrade pip uv
-          uv pip install .[diffusers,tests]
+          uv pip install .[tests]
```
Comment (rkazants) [inline .github/workflows/test_offline.yaml]: why don't we install diffusers to validate?

File: optimum/exporters/openvino/model_configs.py (hunk 14 above)
Comment (rkazants) [reply optimum/exporters/openvino/model_configs.py:864]: can we regenerate tiny-model for this and then remove `MAX_TRANSFORMERS_VERSION`?

File: optimum/exporters/openvino/model_patcher.py [hunk 38]
```diff
@@ -260,6 +337,13 @@ def __enter__(self):
             # non-stateful models on cpu and stateful models on npu
             ALL_MASK_ATTENTION_FUNCTIONS.register("sdpa", eager_mask_without_vmap)
 
+        if is_transformers_version(">=", "5"):
+            for module in self._model.modules():
+                rope_type = getattr(module, "rope_type", None)
+                if rope_type == "longrope" and isinstance(getattr(module, "config", None), RotaryEmbeddingConfigMixin):
```
Comment (rkazants) [inline optimum/exporters/openvino/model_patcher.py:343]: this is a cool thing to have it in the common patcher. It will be available not only for phi models

File: setup.py [hunk 39]
```diff
@@ -69,7 +70,7 @@
 
 EXTRAS_REQUIRE = {
     "nncf": ["nncf>=2.19.0"],
-    "openvino": ["nncf>=2.19.0", "openvino>=2025.4.0", "openvino-tokenizers>=2025.4.0"],
+    "openvino": ["nncf>=2.19.0", "openvino>=2025.3.0", "openvino-tokenizers>=2025.3.0"],
```
Comment (rkazants) [inline setup.py]:
```suggestion
    "openvino": ["nncf>=2.19.0", "openvino>=2026.0.0", "openvino-tokenizers>=2026.0.0"],
```

File: setup.py [hunk 40]
```diff
@@ -28,12 +28,13 @@
...
-    "optimum-onnx@git+https://github.com/huggingface/optimum-onnx.git@main",
-    "transformers>=4.45,<4.58",
+    "optimum-onnx@git+https://github.com/huggingface/optimum-onnx.git@xadupre/transformers5",
+    "transformers>=4.45,<5.1",
     "setuptools",
+    "huggingface-hub>=0.23.2,<2.0",
     "nncf>=2.19.0",
-    "openvino>=2025.4.0",
-    "openvino-tokenizers>=2025.4.0",
+    "openvino>=2025.4.0,<2026.1",
```
Comment (rkazants) [inline setup.py]: misaligned with extras

File: tests/openvino/test_quantization.py [hunk 41]
```diff
@@ -1226,6 +1235,8 @@ def test_filtered_architectures(cls):
             expected.add("qwen3_vl")
         if is_transformers_version(">=", "4.54"):
             expected.update({"llava-qwen2", "phi3_v", "minicpmo"})
+        if is_transformers_version(">=", "5"):
+            expected.update({"llama4", "llava_next_video", "minicpmv", "internvl_chat", "exaone4"})
```
Comment (rkazants) [inline tests/openvino/test_quantization.py:1239]: I think we should support exaone4 model for transformers v5. Is it possible to fix please?

File: setup.py [hunk 42]
```diff
@@ -52,10 +53,10 @@
     "transformers_stream_generator",
     "einops",
     "tiktoken",
-    "sentence-transformers",
+    "sentence-transformers<5.4.0",
```
Comment (echarlaix) [inline setup.py:56]: unrelated to this PR, latest sentence-transformers https://github.com/huggingface/sentence-transformers/releases/tag/v5.4.0 is breaking export, will add a fix in a separate PR

File: .github/workflows/test_openvino.yml (hunk 24 above)
Comment (echarlaix) [reply .github/workflows/test_openvino.yml:62]: @rkazants this was added to fix the seg fault https://github.com/huggingface/optimum-intel/actions/runs/24123066821/job/70381215257 we have when running test_modeling.py as discussed in https://github.com/huggingface/optimum-intel/pull/1589/changes#r2827232852

File: .github/workflows/test_offline.yaml (hunk 37 above)
Comment (echarlaix) [reply .github/workflows/test_offline.yaml]: good catch, added back in https://github.com/huggingface/optimum-intel/pull/1589/changes/58b1e82852b640fcdf8866d5bb2dfec8aa64ab60

File: setup.py (hunk 40 above)
Comment (echarlaix) [reply setup.py]: good catch fixed in https://github.com/huggingface/optimum-intel/pull/1589/changes/1bb32a0a0a5caec6d9e6341b5e5487c37bd2e5a4

File: tests/openvino/test_quantization.py (hunk 41 above)
Comment (echarlaix) [reply tests/openvino/test_quantization.py:1239]: @rkazants let's not block v5 support any longer, we can add update exaone4 `MAX_TRANSFORMERS_VERSION` later on

File: setup.py (hunk 36 above)
Comment (echarlaix) [reply setup.py]: cc @rkazants

File: setup.py [hunk 43]
```diff
@@ -28,12 +28,13 @@
 
 INSTALL_REQUIRE = [
     "torch>=2.1",
-    "optimum-onnx@git+https://github.com/huggingface/optimum-onnx.git@main",
-    "transformers>=4.45,<4.58",
+    "optimum-onnx@git+https://github.com/huggingface/optimum-onnx.git@xadupre/transformers5",
```
Comment (rkazants) [inline setup.py]: this is not good to use developer branch. I still think to remove this dependency from optimum-onnx at all.
Let us do it in separate PR
