### PR TITLE
Fix gemma3 and llava patches for transformers 4.52

### LINKED ISSUE #1398: llava-v1.6-mistral-7b-hf export failure
`optimum-cli export openvino --model llava-hf/llava-v1.6-mistral-7b-hf ./i/llava-v1.6-mistral-7b-hf --trust-remote-code --weight-format fp16` fails with
```
Traceback (most recent call last):
  File "/home/vzlobin/z/e/bin/optimum-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/commands/optimum_cli.py", line 208, in main
    service.run()
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/commands/export/openvino.py", line 577, in run
    main_export(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/__main__.py", line 453, in main_export
    submodel_paths = export_from_model(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 786, in export_from_model
    export_models(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 557, in export_models
    export(
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 195, in export
    return export_pytorch(
           ^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/convert.py", line 457, in export_pytorch
    with patcher:
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/optimum/exporters/openvino/model_patcher.py", line 777, in __exit__
    for layer in self._model.model.layers:
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vzlobin/z/e/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1940, in __getattr__
    raise AttributeError(
AttributeError: 'LlavaNextModel' object has no attribute 'layers'
```
for `transformers` 4.52.3 or 4.53.3. Works with 4.51.3.

### LINKED ISSUE #1405: 'Gemma3ForCausalLM' object has no attribute '_update_causal_mask_mm' with transformers-4.51.3
Image

 [Transformers 4.53 support by IlyasMoutawwakil · Pull Request #1377 · huggingface/optimum-intel](https://github.com/huggingface/optimum-intel/pull/1377/files)
This latest optimum-intel PR removed update_causal_mask_mm, and CI got issue for this with transformers-4.51.3.
**_ERROR:openvino.frontend.pytorch.utils:Failed to build model wrapper.",
"'Gemma3ForCausalLM' object has no attribute '_update_causal_mask_mm'"_**
log in details:
[Enable gemma3-4b-it in VLM Pipeline · openvinotoolkit/openvino.genai@048b649](https://github.com/openvinotoolkit/openvino.genai/actions/runs/16671424051/job/47241334439?pr=2340)

### PR DESCRIPTION
**Pull request by IlyasMoutawwakil**
# What does this PR do?

Fixes #1405 for transfoemrs 4.51
Fixes #1398 and adds a test for llava-next-mistral

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

File: tests/openvino/utils_tests.py [hunk 1]
```diff
@@ -101,6 +101,7 @@
     "llama4": "katuni4ka/tiny-random-llama-4-8E",
     "llava": "katuni4ka/tiny-random-llava",
     "llava_next": "katuni4ka/tiny-random-llava-next",
+    "llava_next_mistral": "/home/ilyas/optimum-intel/tiny-llava-next-mistral",
```
Comment (sammysun0711) [inline tests/openvino/utils_tests.py]: It suppose to be a huggingface repo instead of local path, you may consider upload this `tiny-llava-next-mistral` to your hf repo. Thanks.

Comment (IlyasMoutawwakil) [reply tests/openvino/utils_tests.py]: Hi ! yes I did [upload it before pushing](https://huggingface.co/optimum-internal-testing/tiny-random-llava-next-mistral/tree/main) but forgot to change this line. I would've asked for a review if the PR was ready ☺️. Thanks.
